### ISSUE TITLE
Announce List Support

### ISSUE THREAD

**Issue by SpandanGiri** [SpandanGiri/SPARK-Torrent#3]
Currently we are only using the tracker url from announce property from torrent file. 
If it fails we will use the consecutive urls from the announce-list.

After a timeout of 5s we will hit a new announce url.

**Comment by Arkoprovo08** [comment]
Created a list of announce urls and port numbers. Checking for announce request is done for all announce urls. If request is not recieved in 5 secs timeout is being triggered.   
The issue has been solved.
